development:
  adapter: mysql2
  database: everest_dev
  username: root
  password: root
  host: 127.0.0.1
  encoding: utf8
  collation: utf8_unicode_ci
  socket: /tmp/mysql.sock


test:
  adapter: mysql2
  database: everst_test
  username: root
  password: root
  host: 127.0.0.1
  encoding: utf8
  collation: utf8_unicode_ci
  socket: /tmp/mysql.sock
